apiVersion: v1
kind: ConfigMap
metadata:
  name: game-demo
data:
  # property-like keys; each key maps to a simple value
  player_initial_lives: "5"
  ui_properties_file_name: "user-interface.properties"

  # file-like keys
  game.properties: |
    user.type=sudha
    enemy.types=aliens,monsters
    player.maximum-lives=5    
  user-interface.properties: |
    user.text=good
    color.good=purple
    color.bad=yellow
    allow.textmode=true   
