apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: jenkinsdaemon
  labels:
    app: jenkinsdeploy
spec:
  selector: 
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - image: jenkins/jenkins:2.60.2
          name: jenkinsimage
            #  - image: nginx
            #name: nginx 

