apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkinsdeploy-hostpath
  labels:
    app: jenkinsdeploy-hostpath
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector: 
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      nodeSelector:
        env: dev
      containers:
        - image: jenkins/jenkins:lts
          name: jenkinsimage
          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home
      volumes:
        - name: jenkins-home
          hostPath:
            path: /home/ubuntu/jenkins_data
            type: Directory

