apiVersion: v1
kind: Service
metadata:
  name: externalip
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8020
      targetPort: 8080
  selector:
    app: jenkins
  externalIPs:
    - 10.0.0.10
