apiVersion: v1
kind: Service
metadata:
  name: nodeport
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 8020
      targetPort: 8080
      nodePort: 30123
  selector:
    app: jenkins
       
