apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkinsdeploy
  labels:
    app: jenkinsdeploy
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - image: jenkins/jenkins:2.60.2
          name: jenkinsimage
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: name
                    operator: In
                    values:
                      - 75south
                      - 247south
